# Generated by Django 3.2.9 on 2021-11-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_notebook_smartphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='processor_frequency',
            field=models.CharField(max_length=9, verbose_name='Частота процессора'),
        ),
    ]
